services:
  mssql:
    build:
      context: ./mssql
      dockerfile: Dockerfile
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Yukon900
    ports:
      - 1433:1433

  oracle-xe:
    image: gvenzl/oracle-xe:21-faststart
    environment:
      ORACLE_RANDOM_PASSWORD: yes
      ORACLE_DATABASE: siard
      APP_USER: siard
      APP_USER_PASSWORD: siard
    ports:
      - 1521:1521

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  mariadb:
    image: mariadb:10.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: public
      MYSQL_USER: public
      MYSQL_PASSWORD: public
    ports:
      - 3306:3306

