#-----------------------------------------------------------------------
# DO NOT USE WHITESPACES IN PATHS; JAVA DOES NOT LIKE THEM:
# Windows developers:
# If you want to use backslashes (\) then you must repeat them twice, e.g.
# c:\\foo\\bar
# or - in path names - you can just use slashes, e.g.
# c:/foo/bar
#-----------------------------------------------------------------------
#-----------------------------------------------------------------------
# The deployment folder to which the binaries are to be unzipped.
dirdeploy=./target
#dirdeploy=/home/hartwig/test
#dirdeploy=D:/Temp

#-----------------------------------------------------------------------
# The bootstrap class (run-time jar) for compiling code compatible with JSE 1.8.
#java8rtjar=C:/Program Files/Java/jdk1.8.0_144/jre/lib/rt.jar
#java8rtjar=/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar
java8rtjar=C:/myProgs/java/current/jre/lib/rt.jar

# ----------------------------------------------------------------------
# db connection properties
# if dbuser is undefined, no tests with a MySQL database will be run by build 
dbhost=127.0.0.1
dbport=3306
dbcatalog=testschema
dbuser=testuser
dbpassword=testpwd
dbauser=root
dbapassword=rootpwd

#-----------------------------------------------------------------------
# BLOB sample files (same number of PNGs and FLACs, at most 10 per type)
blobpng0=src/test/resources/png-1.png
#blobpng2=D:/SFPD/18/000002/18-000002A.png
#blobpng3=D:/SFPD/18/000002/18-000002B.png
#blobpng1=D:/SFPD/18/000001/18-000001B.png
#blobpng4=D:/SFPD/18/000003/18-000003A.png
#blobpng5=D:/SFPD/18/000003/18-000003B.png
#blobpng6=D:/SFPD/18/000004/18-000004A.png
#blobpng7=D:/SFPD/18/000004/18-000004B.png
#blobpng8=D:/SFPD/18/000005/18-000005A.png
#blobpng9=D:/SFPD/18/000005/18-000005B.png

blobflac0=src/test/resources/sample1.flac
#blobflac1=D:/SFPD/18/000001/18-000001B.flac
#blobflac2=D:/SFPD/18/000002/18-000002A.flac
#blobflac3=D:/SFPD/18/000002/18-000002B.flac
#blobflac4=D:/SFPD/18/000003/18-000003A.flac
#blobflac5=D:/SFPD/18/000003/18-000003B.flac
#blobflac6=D:/SFPD/18/000004/18-000004A.flac
#blobflac7=D:/SFPD/18/000004/18-000004B.flac
#blobflac8=D:/SFPD/18/000005/18-000005A.flac
#blobflac9=D:/SFPD/18/000005/18-000005B.flac