# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build project

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'zulu'
          java-package: "jdk+fx"
          cache: "gradle"
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew build -Djava.awt.headless=true -Dtestfx.headless=true --no-daemon
      - name: Prepare build artifacts (zip) for download
        uses: actions/upload-artifact@v3
        with:
          name: siard-suite-1.0-SNAPSHOT
          path: build/distributions/siard-suite-1.0-SNAPSHOT.zip
