name: Test Suite

on:
  push:
    branches: [ "main", "feature/*", "issue/*", "doc/*" ]
  pull_request:
    branches: [ "main" ]

env:
  TZ: Europe/Zurich

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          java-package: "jdk+fx"
          cache: "gradle"
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Show version
        run: ./gradlew cV
      - name: Compile all modules
        run: ./gradlew compileJava compileTestJava -x test

  unit-tests:
    needs: compile
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - enter-utilities
          - zip64-file
          - sql-parser
          - siard-api
          - jdbc-base
          - jdbc-oracle
          - jdbc-access
          - jdbc-db2
          - jdbc-mssql
          - jdbc-mysql
          - jdbc-postgres
          - siard-cmd
          - siard-suite-app
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          java-package: "jdk+fx"
          cache: "gradle"
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Test ${{ matrix.module }}
        run: ./gradlew :${{ matrix.module }}:test -Djava.awt.headless=true -Dtestfx.headless=true
      - name: Upload test reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-${{ matrix.module }}
          path: ${{ matrix.module }}/build/reports/tests/
