# understands how to build platform specific binaries that ship with the necessary java runtime
name: Package Platform Specific Runtimes and Installer

on:
  push:
    branches: [ "main", "feature/513-include-jre" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
      fail-fast: false
    name: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'zulu'
          java-package: "jdk+fx"
          cache: "gradle"
      - name: Echo JAVA_HOME
        run: echo $JAVA_HOME
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute build
        run: ./gradlew --info --stacktrace build
      - name: Execute runtime
        run: ./gradlew --info --stacktrace runtime
      - name: Execute jpackage
        run: ./gradlew --info --stacktrace jpackage
      - name: Upload DMG as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: hellofx-jdk${{ matrix.java }}-${{ matrix.os }}-dmg
          path: build/jpackage/*.dmg
      - name: Upload EXE as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: siard-suite-${{ matrix.os }}-exe
          path: build/jpackage/*.exe
      - name: Upload MSI as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: siard-suite-${{ matrix.os }}-msi
          path: build/jpackage/*.msi
      - name: Upload DEB as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: siard-suite-${{ matrix.os }}-deb
          path: build/jpackage/*.deb
      - name: Upload RPM as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: siard-suite-${{ matrix.os }}-rpm
          path: build/jpackage/*.rpm