# understands how to build platform specific binaries that ship with the necessary java runtime
name: Create standalone deliverables for SIARD (installers and distributions with runtimes)

on:
  tag:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        java: [ '18' ]
      fail-fast: false
    name: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          java-package: "jdk+fx"
          cache: "gradle"
      - name: Echo JAVA_HOME
        run: echo $JAVA_HOME
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute build
        run: ./gradlew build --no-daemon
      - name: Execute runtime
        run: ./gradlew runtime --no-daemon
      - name: Execute jpackage
        run: ./gradlew jpackage --no-daemon
      - name: Upload DMG as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: siard-suite-jdk-${{ matrix.java }}-${{ matrix.os }}-dmg
          path: build/jpackage/*.dmg
      - name: Upload EXE as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: siard-suite-jdk-${{ matrix.java }}-${{ matrix.os }}-exe
          path: build/jpackage/*.exe
      - name: Upload MSI as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: siard-suite-jdk-${{ matrix.java }}-${{ matrix.os }}-msi
          path: build/jpackage/*.msi
      - name: Upload DEB as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: siard-suite-jdk-${{ matrix.java }}-${{ matrix.os }}-deb
          path: build/jpackage/*.deb
      - name: Upload RPM as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: siard-suite-jdk-${{ matrix.java }}-${{ matrix.os }}-rpm
          path: build/jpackage/*.rpm
      - name: Upload bundled package
        uses: actions/upload-artifact@v2
        with:
          name: siard-suite-${matrix.os}
          path: build/install/siard-suite